__default__:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 12:00:00
run_hisat3_pe:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    6G
    tmem:   6G
    h_rt: 90:00:00
run_hisat3_se:
    submission_string: " "
    h_vmem:    24G
    tmem:   24G
    h_rt: 90:00:00
conversion_table:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    6G
    tmem:   6G
    h_rt: 72:00:00
tag_bams:
    submission_string: " "
    h_vmem:    24G
    tmem:   24G
    h_rt: 72:00:00
sort_bams:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 72:00:00
sort_histat:
    submission_string: " "
    h_vmem:    16G
    tmem:   16G
    h_rt: 72:00:00
filter_conversion:
    submission_string: " "
    h_vmem:    16G
    tmem:   16G
    h_rt: 12:00:00
split_conversion:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 12:00:00