__default__:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 04:00:00
run_hisat3_pe:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    12G
    tmem:   12G
    h_rt: 12:00:00
stability_splice_count:
    submission_string: "-pe smp 8 -R y"
    h_vmem:    3G
    tmem:   3G
    h_rt: 20:00:00
run_hisat3_se:
    submission_string: " "
    h_vmem:    24G
    tmem:   24G
    h_rt: 90:00:00
conversion_table:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    6G
    tmem:   6G
    h_rt: 72:00:00
tag_bams:
    submission_string: " "
    h_vmem:    24G
    tmem:   24G
    h_rt: 72:00:00
sort_bams:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 72:00:00
sort_histat:
    submission_string: " "
    h_vmem:    16G
    tmem:   16G
    h_rt: 72:00:00
filter_conversion:
    submission_string: " "
    h_vmem:    16G
    tmem:   16G
    h_rt: 12:00:00
split_conversion:
    submission_string: " "
    h_vmem:    8G
    tmem:   8G
    h_rt: 12:00:00
call_snp_mask:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    10G
    tmem:   10G
    h_rt: 24:00:00
call_md_tag:
    submission_string: "-pe smp 4 -R y"
    h_vmem:    4G
    tmem:   4G
    h_rt: 05:00:00