sampleCSVpath: /SAN/vyplab/alb_projects/data/bdnf_4su_i3lmn/trial_run/bdnf_trialrun.csv
project_top_level:   /SAN/vyplab/NYGC_ALSFTD/temporary_bdnf/

end_type: "se"
strandedness: "F"

# sampleCSVpath: /SAN/vyplab/alb_projects/data/4su_better_design_ward_ipsc/foursu_full_experiment_kd.csv
# #master directory in which output from individual rules is stored (within individual subdirectories, unless overriden below)
# project_top_level:  /SAN/vyplab/NYGC_ALSFTD/temporary_4su/
# end_type: "pe"
# strandedness: "FR"
#below you can specify the names of rulesubdirectories
#if the provided path string is RELATIVE, the string will be joined with project_top_level to form the output directory path
#if the provided path string is ABSOLUTE, the output for the given rule will be stored in the provided string (NOT WITHIN project_top_level)
#In practice leaving as relative defaults is best option...
fastp_trimmed_output_folder: fastp_trimmed/
merged_fastq_folder: fastp_trimmed/

histat3n_output_folder: histat3n/

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/GRCh38.primary_assembly.genome.fa
fasta_sizes: /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/GRCh38.primary_assembly.genome.size